name: Playwright Tests (Pull Request)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install -D @playwright/test

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test
